# Generated by Django 5.1.5 on 2025-02-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocols", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="protocol-files/"),
        ),
    ]
