# Generated by Django 5.1.5 on 2025-02-02 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("pre_registrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientadmission",
            name="pre_registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admissions",
                to="pre_registrations.preregistration",
                verbose_name="Pre-Registration",
            ),
        ),
    ]
