# Generated by Django 5.1.5 on 2025-02-02 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Resource Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Type",
                "verbose_name_plural": "Resource Types",
            },
        ),
        migrations.CreateModel(
            name="ResourceUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_quantity",
                    models.PositiveIntegerField(verbose_name="Resource Quantity"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Usage Start Time"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Usage End Time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Usage",
                "verbose_name_plural": "Resource Usages",
            },
        ),
        migrations.CreateModel(
            name="OccupancyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occupied_quantity",
                    models.PositiveIntegerField(verbose_name="Occupied Quantity"),
                ),
                (
                    "occupancy_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Occupancy Percentage",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Date"
                    ),
                ),
                (
                    "resource_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupancy_histories",
                        to="occupancy.resourcetype",
                        verbose_name="Resource Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Occupancy History",
                "verbose_name_plural": "Occupancy Histories",
            },
        ),
        migrations.CreateModel(
            name="MedicalCenterCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_quantity",
                    models.PositiveIntegerField(verbose_name="Total Quantity"),
                ),
                (
                    "resource_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacities",
                        to="occupancy.resourcetype",
                        verbose_name="Resource Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Center Capacity",
                "verbose_name_plural": "Medical Center Capacities",
            },
        ),
    ]
