# Generated by Django 5.1.5 on 2025-02-02 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("occupancy", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceusage",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_usages",
                to="patients.patientadmission",
                verbose_name="Admission",
            ),
        ),
        migrations.AddField(
            model_name="resourceusage",
            name="resource_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usages",
                to="occupancy.resourcetype",
                verbose_name="Resource Type",
            ),
        ),
    ]
