# Generated by Django 5.1.5 on 2025-02-02 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreRegistrationMedicalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Reason")),
                (
                    "allergies",
                    models.TextField(blank=True, null=True, verbose_name="Allergies"),
                ),
                (
                    "preexisting_conditions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Preexisting Conditions"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("expired", "Expired"),
                            ("attended", "Attended"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Date"),
                ),
            ],
            options={
                "verbose_name": "Pre-Registration Medical Info",
                "verbose_name_plural": "Pre-Registration Medical Infos",
            },
        ),
        migrations.CreateModel(
            name="ThirdParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(max_length=100, verbose_name="Relationship"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "contact_number",
                    models.CharField(max_length=20, verbose_name="Contact Number"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Date"),
                ),
            ],
            options={
                "verbose_name": "Third Party",
                "verbose_name_plural": "Third Parties",
            },
        ),
        migrations.CreateModel(
            name="PreRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("expired", "Expired"),
                            ("attended", "Attended"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Date"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_registrations",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "medical_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_registrations",
                        to="pre_registrations.preregistrationmedicalinfo",
                        verbose_name="Medical Info",
                    ),
                ),
                (
                    "third_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_registrations",
                        to="pre_registrations.thirdparty",
                        verbose_name="Third Party",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre-Registration",
                "verbose_name_plural": "Pre-Registrations",
            },
        ),
    ]
