# Generated by Django 5.1.5 on 2025-02-14 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_registrations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preregistrationmedicalinfo",
            name="status",
        ),
        migrations.AlterField(
            model_name="preregistration",
            name="third_party",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_registrations",
                to="pre_registrations.thirdparty",
                verbose_name="Third Party",
            ),
        ),
    ]
