# Generated by Django 5.1.5 on 2025-03-02 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_registrations", "0002_remove_preregistrationmedicalinfo_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("canceled", "Canceled"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                ],
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="preregistration",
            name="third_party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_registrations",
                to="pre_registrations.thirdparty",
                verbose_name="Third Party",
            ),
        ),
    ]
