name: Run Flake8 on Notifications Consumer

on:
  push:
    branches:
      - main
    paths:
      - Proyecto/notifications_consumer/**
  pull_request:
    branches:
      - main
    paths:
      - Proyecto/notifications_consumer/**

jobs:
  consumer-flake8:
    name: Run Flake8 on Notifications Consumer
    runs-on: ubuntu-latest
    container:
      image: python:3.11.10
    defaults:
      run:
        working-directory: Proyecto/notifications_consumer
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python Environment and Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate && pip install -r requirements.txt

      - name: Run Flake8
        run: |
          source venv/bin/activate && flake8 --config=.flake8
