name: Django Backend Lint and Tests

on:
  push:
    branches:
      - main
    paths:
      - Proyecto/django-backend/centro_medico/**
  pull_request:
    branches:
      - main
    paths:
      - Proyecto/django-backend/centro_medico/**

jobs:
  backend-flake8-tests:
    name: Run Flake8 and Django Tests on Backend
    runs-on: ubuntu-latest
    container:
      image: python:3.11.10
    defaults:
      run:
        working-directory: Proyecto/django-backend/centro_medico
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .env file
        run: |
          echo "DEBUG=True" > .env
          echo "SECRET_KEY=supersecret" >> .env
          echo "DATABASE_URL=db.sqlite3" >> .env
          echo "FRONTEND_URL=http://localhost:3000" >> .env
          echo "LANDING_URL=http://localhost:3000" >> .env
          echo "BACKEND_URL=localhost" >> .env

      - name: Setup Python Environment and Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate && pip install -r requirements.txt

      - name: Run Flake8
        run: |
          source venv/bin/activate && flake8 --config=.flake8

      - name: Run Migrations
        run: |
          source venv/bin/activate && python manage.py migrate --noinput

      - name: Run Django Tests
        run: |
          source venv/bin/activate && python manage.py test
